%dev.quarkus.keycloak.devservices.enabled=false

quarkus.oidc.auth-server-url=http://localhost:8080/realms/ecommerce
quarkus.oidc.client-id=auth-service
quarkus.oidc.credentials.secret=ISI_CLIENT_SECRET_DARI_STEP_SEBELUMNYA

quarkus.oidc.application-type=service

quarkus.oidc.token.audience=auth-service

quarkus.http.auth.permission.public.paths=/auth,/q/*
quarkus.http.auth.permission.public.policy=permit

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated