package com.ecommerce.auth.dao;

import com.ecommerce.auth.exception.AccountException;
import com.ecommerce.auth.exception.IdentityProviderUnavailableException;
import com.ecommerce.auth.model.Account;
import com.ecommerce.auth.model.AccountRole;
import com.ecommerce.auth.model.AccountUpdate;
import com.ecommerce.auth.model.NewAccount;
import com.ecommerce.auth.model.RawPassword;

/**
 * Contract for managing accounts in the identity store.
 *
 * <p>
 * The counterpart of {@link IdentityProviderDao}: that one asks "are these
 * credentials good?", this one owns the lifecycle of the account behind them.
 * They are separate interfaces because a class that only logs users in has no
 * business being recompiled — or mocked — when the delete signature changes
 * (Interface Segregation Principle).
 *
 * <p>
 * The three methods here <em>do</em> belong together, though: create, update and
 * delete are the same aggregate at three points in its life, and every caller
 * that has one of them realistically needs the others. Splitting them further
 * would be ceremony, not segregation.
 *
 * <p>
 * As with logging in, none of this touches the Keycloak database directly — see
 * {@link IdentityProviderDao} for why. The concrete implementation calls the
 * Admin REST API, which enforces the realm's password policy and keeps the
 * credential hashing scheme Keycloak's own business.
 *
 * @see com.ecommerce.auth.dao.keycloak.KeycloakAccountProviderDao
 */
public interface AccountProviderDao {

    /**
     * Creates the account and sets its password in one call.
     *
     * <p>
     * One call rather than two on purpose: a separate "now set the password"
     * request could fail on its own and leave behind an account with no
     * credential, holding the username and email address against the retry.
     *
     * @param newAccount the profile to create
     * @param password   the password to give it, generated by the caller
     * @return the created account, as the provider stored it — including the id
     *         it assigned, which is also the {@code sub} claim of every token
     *         later issued for it
     * @throws AccountException                    the username or email is taken,
     *                                             or the data was rejected
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    Account doCreate(NewAccount newAccount, RawPassword password);

    /**
     * Grants a realm role to an existing account.
     *
     * <p>
     * Separate from {@link #doCreate} against the reasoning above, and for a
     * reason outside this service's control: Keycloak's create-user call carries
     * a credential but ignores roles, so the role can only be a second request.
     * The caller therefore has to treat the two as one unit and undo the create
     * when this fails — see {@code AccountServiceImpl#doRegister}, which does.
     *
     * <p>
     * Granting a role the account already holds is a no-op rather than an error,
     * so a retry of a half-finished registration is safe.
     *
     * @param accountId the provider's id for the account
     * @param role      the role to grant
     * @throws AccountException                    no such account, or no such role
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doAssignRole(String accountId, AccountRole role);

    /**
     * Reads a single account by the provider's id.
     *
     * <p>
     * Needed because the account endpoints address an account by id while
     * verifying a password needs its username — the two are different keys for
     * the same record, and only the provider knows the mapping.
     *
     * @param accountId the provider's id for the account
     * @return the account as the provider stored it
     * @throws AccountException                    no such account
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    Account doFindById(String accountId);

    /**
     * Replaces the account's password.
     *
     * <p>
     * Whether the caller was entitled to do this is settled before we get here —
     * see {@code CurrentAccount} and {@code CurrentPasswordVerifier}. This
     * method only writes.
     *
     * @param accountId   the provider's id for the account
     * @param newPassword the password to store
     * @throws AccountException                    no such account, or the realm
     *                                             password policy refused the value
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doChangePassword(String accountId, RawPassword newPassword);

    /**
     * Applies the non-null fields of {@code update} to the account, leaving every
     * other field as it was.
     *
     * @param accountId the provider's id for the account
     * @param update    the fields to change
     * @throws AccountException                    no such account, or the data was rejected
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doUpdate(String accountId, AccountUpdate update);

    /**
     * Removes the account.
     *
     * <p>
     * Access tokens already issued for it stay valid until they expire — they are
     * self-contained JWTs and no provider can recall them — so a deleted account
     * can still be seen making calls for up to one token lifetime.
     *
     * @param accountId the provider's id for the account
     * @throws AccountException                    no such account
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doDelete(String accountId);
}
