package com.ecommerce.auth.dao;

import com.ecommerce.auth.exception.AccountException;
import com.ecommerce.auth.exception.IdentityProviderUnavailableException;
import com.ecommerce.auth.model.Account;
import com.ecommerce.auth.model.AccountRole;
import com.ecommerce.auth.model.AccountUpdate;
import com.ecommerce.auth.model.NewAccount;
import com.ecommerce.auth.model.RawPassword;

/**
 * Contract for managing accounts in the identity store.
 * @see com.ecommerce.auth.dao.keycloak.KeycloakAccountProviderDao
 */
public interface AccountProviderDao {

    /**
     * Creates the account and sets its password in one call.
     * @param newAccount the profile to create
     * @param password   the password to give it, generated by the caller
     * @return the created account, as the provider stored it — including the id
     *         it assigned, which is also the {@code sub} claim of every token
     *         later issued for it
     * @throws AccountException                    the username or email is taken,
     *                                             or the data was rejected
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    Account doCreate(NewAccount newAccount, RawPassword password);

    /**
     * Grants a realm role to an existing account.
     * @param accountId the provider's id for the account
     * @param role      the role to grant
     * @throws AccountException                    no such account, or no such role
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doAssignRole(String accountId, AccountRole role);

    /**
     * Reads a single account by the provider's id.
     * @param accountId the provider's id for the account
     * @return the account as the provider stored it
     * @throws AccountException                    no such account
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    Account doFindById(String accountId);

    /**
     * Replaces the account's password.
     * @param accountId   the provider's id for the account
     * @param newPassword the password to store
     * @throws AccountException                    no such account, or the realm
     *                                             password policy refused the value
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doChangePassword(String accountId, RawPassword newPassword);

    /**
     * Applies the non-null fields of {@code update} to the account, leaving every
     * other field as it was.
     *
     * @param accountId the provider's id for the account
     * @param update    the fields to change
     * @throws AccountException                    no such account, or the data was rejected
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doUpdate(String accountId, AccountUpdate update);

    /**
     * Removes the account.
     * @param accountId the provider's id for the account
     * @throws AccountException                    no such account
     * @throws IdentityProviderUnavailableException the provider could not be reached
     */
    void doDelete(String accountId);
}
